//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoordinateLoadOption.StringResources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoordinateLoadOption.StringResources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Add Mode 的當地語系化字串。
        /// </summary>
        internal static string addMode {
            get {
                return ResourceManager.GetString("addMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Body Overlay 的當地語系化字串。
        /// </summary>
        internal static string bodyOverlay {
            get {
                return ResourceManager.GetString("bodyOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Chara Overlays 的當地語系化字串。
        /// </summary>
        internal static string charaOverlay {
            get {
                return ResourceManager.GetString("charaOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear Acc. 的當地語系化字串。
        /// </summary>
        internal static string clearAccWord {
            get {
                return ResourceManager.GetString("clearAccWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Accessories 的當地語系化字串。
        /// </summary>
        internal static string ClothesKind_accessories {
            get {
                return ResourceManager.GetString("ClothesKind_accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bottoms 的當地語系化字串。
        /// </summary>
        internal static string ClothesKind_bot {
            get {
                return ResourceManager.GetString("ClothesKind_bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bra 的當地語系化字串。
        /// </summary>
        internal static string ClothesKind_bra {
            get {
                return ResourceManager.GetString("ClothesKind_bra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Gloves 的當地語系化字串。
        /// </summary>
        internal static string ClothesKind_gloves {
            get {
                return ResourceManager.GetString("ClothesKind_gloves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pantyhose 的當地語系化字串。
        /// </summary>
        internal static string ClothesKind_panst {
            get {
                return ResourceManager.GetString("ClothesKind_panst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Indoor shoes 的當地語系化字串。
        /// </summary>
        internal static string ClothesKind_shoes_inner {
            get {
                return ResourceManager.GetString("ClothesKind_shoes_inner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Outdoor shoes 的當地語系化字串。
        /// </summary>
        internal static string ClothesKind_shoes_outer {
            get {
                return ResourceManager.GetString("ClothesKind_shoes_outer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shorts 的當地語系化字串。
        /// </summary>
        internal static string ClothesKind_shorts {
            get {
                return ResourceManager.GetString("ClothesKind_shorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Socks 的當地語系化字串。
        /// </summary>
        internal static string ClothesKind_socks {
            get {
                return ResourceManager.GetString("ClothesKind_socks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tops 的當地語系化字串。
        /// </summary>
        internal static string ClothesKind_top {
            get {
                return ResourceManager.GetString("ClothesKind_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Empty 的當地語系化字串。
        /// </summary>
        internal static string empty {
            get {
                return ResourceManager.GetString("empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Face Overlay 的當地語系化字串。
        /// </summary>
        internal static string faceOverlay {
            get {
                return ResourceManager.GetString("faceOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Iris Overlay 的當地語系化字串。
        /// </summary>
        internal static string irisOverlay {
            get {
                return ResourceManager.GetString("irisOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lock Hair Acc. 的當地語系化字串。
        /// </summary>
        internal static string lockHairAcc {
            get {
                return ResourceManager.GetString("lockHairAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 When performing coordinate changes in Maker, you may encounter an error here. 
        ///The implementation of changing coordinates optionally is to read and apply the coordinate to the dummy first, and then pick up the wanted parts. 
        ///The design consideration of KKSAPI is that &quot;&quot;only one character will loaded in Maker&quot;&quot;, which causes plugins that rely on KKSAPI to fail to initialize the dummy. 
        ///If you encounter errors, please try to install IllusionFixes.NullChecks, it can easily bypass the situation. 
        ///Since the  [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string makerWarning {
            get {
                return ResourceManager.GetString("makerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ABMX 的當地語系化字串。
        /// </summary>
        internal static string readABMX {
            get {
                return ResourceManager.GetString("readABMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Replace Mode 的當地語系化字串。
        /// </summary>
        internal static string replaceMode {
            get {
                return ResourceManager.GetString("replaceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Toggle Hair Acc. 的當地語系化字串。
        /// </summary>
        internal static string reverseHairAcc {
            get {
                return ResourceManager.GetString("reverseHairAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show Selection 的當地語系化字串。
        /// </summary>
        internal static string showSelection {
            get {
                return ResourceManager.GetString("showSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unrecognized 的當地語系化字串。
        /// </summary>
        internal static string unreconized {
            get {
                return ResourceManager.GetString("unreconized", resourceCulture);
            }
        }
    }
}
